version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-flask-app
    ports:
      - "5252:5252"
    depends_on:
      - redis-server

  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"