services:
  front-end:
    image: softy-pinko/front-end
    ports:
      - "9000:9000"
    build:
      context: front-end
      dockerfile: dockerfile

  back-end:
    image: softy-pinko/back-end
    ports:
      - "5252:5252"
    build:
      context: back-end
      dockerfile: dockerfile