services:
  front-end:
    image: softy-pinko/front-end
    ports:
      - "9000"
    build:
      context: front-end
      dockerfile: Dockerfile

  back-end:
    image: softy-pinko/back-end
    ports:
      - "5252"
    build:
      context: back-end
      dockerfile: Dockerfile

  proxy:
    image: softy-pinko/proxy
    ports:
     - "80:80"
    build:
      context: proxy
      dockerfile: Dockerfile